learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
]

learning_log/learning_logs/urls.py
#define os padrões de url

from django.conf.urls import url

from . import views

urlpatterns = [
    #página inicial
    url(r'^$', views.index, name='index'),
    #página para listar assuntos
    url(r'^topics/$', views.index, name='topics'),
    #página para listar as entradas sobre um assunto
    url(r'^topics/(?P<topic_id>\d+)/$', views.index, name='topic'),
    #página para crair um novo assunto
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
]

learning_log/learning_logs/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    #assunto do tópico
    txt = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        #develve uma representação em string do modelo 
        return self.text


class Entry(models.Model):
    #algo específico aprendido sobre um assunto
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)


    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        # devolve uma representação em string do modelo
        return self.text[:50] + "..."

learning_log/learning_logs/forms.py
from django import forms
from .models import Topic

class TopicForm(forms.ModelsForm):
    class Meta:
        model = Topic
        fiels = ['text']
        labels = {'text': ''}

learning_log/learning_logs/views.py
from django.shortcuts import renderfrom django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Topic
from .forms import TopicForm

# Create your views here.

def index(request):
    #chama a página inicial
    return render(request, 'learning_logs/index.html')

def topics(request):
    #mostra os assuntos
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    #mostra um único assunto e todas as suas entradas
    topic = Topics.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


def new_topic(request):
    #adiciona um novo assunto
    if request.method != 'POST':
        #nenhum dado submetido, cria um formulário em branco
        form = TopicForm()

    else:
        #se recebe dados do POST, processa-os
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))


    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

learning_log/learning_logs/templates/learning_logs/base.html
<!-- tirar o style incorporado na tag depois -->
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>As Fugas de Potira</title>
</head>
<body>
    <header>
        <a style="text-decoration: none" href="{% url 'learning_logs:index' %}">As Fugas de Potira</a>
        <a style="text-decoration: none" href="{% url 'learning_logs:topics' %}">Tópicos</a>
    </header>

{% block content %}{% endblock content %}
</body>




</html>

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Aqui temos nossa primeira fuga, em ré maior, pois estou motivada.</p>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <p>Adicione um novo assunto:</p>

    <form action="{% url 'learning_logs:newtopic' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>Criar</button>
    </form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

<div>
    <h1>Assunto: {{ topic }}</h1>

    <h2> Entradas</h2>

        <ul>
            {% for entry in entries %}
                <li>
                    <p>{{ entry.date_added|date: 'M d, Y H:i' }}</p>
                    <p>{{ entry.text|linebreaks }}</p>
                </li>
            {% empty %}
                <li>Ainda não há nada sobre este assunto</li>
            {% endfor %}
        </ul>
</div>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

<h1>Tópicos</h1>
<ul>
    {% for topic in topics %}
        <li>
            <a href="{% url 'learnig_logs:topic' topic.id %}"> {{ topic }}</a>
        </li>
    {% empty %}
        <li>Nenhum tópico foi adicionado ainda</li>
    {% endfor %}
</ul>

<a href="{% url 'learning_logs:new_topic' %}">Crie um novo assunto:</a>

{% endblock content %}